[package]
name = "macrde-compositor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
macrde-core = { path = "../core" }
macrde-ipc = { path = "../ipc" }
macrde-render = { path = "../render" }
macrde-x11 = { path = "../x11" }

anyhow = "1.0.102"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tokio = { version = "1.0", features = ["net", "time",  "io-util", "rt", "rt-multi-thread", "macros", "sync"] }
bincode = "2.0.0"