[package]
name = "macrde-ipc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bincode = { version = "2.0.0", features = ["serde"] }
macrde-core = { path = "../core" }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"

