[package]
name = "de-mvp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "de-mvp"
path = "src/main.rs"

[dependencies]
de-core = { path = "../de-core" }
de-x11 = { path = "../de-x11" }
de-render = { path = "../de-render" }
xcb = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
