[package]
name = "de-ipc-bus"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "de-ipc-bus"
path = "src/main.rs"

[dependencies]
de-ipc = { path = "../de-ipc" }
tokio = { workspace = true }
tokio-stream = "0.1"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }