[package]
name = "macrde-wm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.102"
bincode = "2.0.0"
macrde-core = { path = "../core" }
macrde-ipc = { path = "../ipc" }
macrde-x11 = { path = "../x11" }
thiserror = "2.0.18"
tokio = "1.51.1"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
